version: "3.5"
services:
  review-php-apache:
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    ports:
      - 8888:80
    volumes:
      - type: bind
        source: "./php-apache/000-default.conf"
        target: "/etc/apache2/sites-enabled/000-default.conf"
      - type: bind
        source: "./php-apache/app"
        target: "/var/www/docker_review"
    depends_on:
      - review-mysql

  review-mysql:
    image: mysql@sha256:45ad5952e4f304d39aedb02caf7e0afc30a310e66f7ab60af8acf20fd4a0f54c
    environment:
      - MYSQL_ROOT_PASSWORD=e2QNqCUd
      - MYSQL_DATABASE=docker_review